# Find SIMPROP. Sets
# SIMPROP_FOUND = true if SIMPROP is found
# SIMPROP_INCLUDE_DIR = simprop.h
# SIMPROP_LIBRARIES = libsimprop.a .so

find_path(SIMPROP_INCLUDE_DIR simprop.h)
find_library(SIMPROP_LIBRARIES simprop)

set(SIMPROP_FOUND FALSE)
if(SIMPROP_INCLUDE_DIR AND SIMPROP_LIBRARIES)
    set(SIMPROP_FOUND TRUE)
    MESSAGE(STATUS "SIMPROP: Found!")
else()
    MESSAGE(STATUS "SIMPROP: NOT Found!")
endif()

MESSAGE(STATUS "  Include:     ${SIMPROP_INCLUDE_DIR}")
MESSAGE(STATUS "  Library:     ${SIMPROP_LIBRARIES}")

mark_as_advanced(SIMPROP_INCLUDE_DIR SIMPROP_LIBRARIES SIMPROP_FOUND)
